x-env-vars: &env_vars
  DB_USERNAME: ct_admin
  DB_PASSWORD: hotdogsfordinner
  DB_NAME: geoconnections
  DB_HOST: host.docker.internal
  DB_PORT: 5432
  KAFKA_SERVER: kafka:9092
  PERSON_HOST: http://api-person:5001/api/persons #http://localhost:5001/api/persons #http://modules-api-person-1:5001/api/persons
  LOCATION_HOST: http://api-locations:5002/api/locations #http://modules-api-locations-1:5002/api/locations
  FRONTEND_PERSON_URL: http://localhost:5001/api/persons
  REACT_APP_FRONTEND_LOCATION_URL: http://localhost:5002/api/locations
networks:
  udaconnect_network:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      <<: *env_vars
    networks:
      - udaconnect_network