apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api-location
  name: udaconnect-api-location
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
    nodePort: 30002
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30005
  selector:
    service: udaconnect-api-location
  type: NodePort
