apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  KAFKA_SERVER: kafka:9092
  KAFKA_TOPIC: location-topic
  KAFKA_CONSUMER_GROUP: location-consumer-group
  PERSON_HOST: http://udaconnect-api-person:5001/api/persons
  
metadata:
  name: db-env