apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    app: kafka  # This should match the labels in your Kafka Deployment
  ports:
    - protocol: TCP
      port: 9092         # Port exposed outside of the service
      targetPort: 9092    # Port that Kafka container listens on
  clusterIP: None  # Optional for headless service; remove if you want a normal ClusterIP service