apiVersion: v1
kind: Service
metadata:
  labels:
    service: ui-udaconnect-app
  name: ui-udaconnect-app
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    service: ui-udaconnect-app
  type: NodePort