x-env-vars: &env_vars
  DB_USERNAME: ct_admin
  DB_PASSWORD: hotdogsfordinner
  DB_NAME: geoconnections
  DB_HOST: host.docker.internal
  DB_PORT: 5432
  PERSON_HOST: http://mb-cd0309-message-passing-projects-starter-api-person-1:5001/api/persons

services:
  api-person:
    #image: mb-cd0309-message-passing-projects-starter-api-person
    #build:
    #  context: ./modules/api-person
    build:
      context: ./api-person
    ports:
      - "5001:5001"
    environment:
      <<: *env_vars


  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"


  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092  # Changed localhost to kafka
    volumes:
      - kafka-data:/var/lib/kafka/data  # <-- Persist Kafka data
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

volumes:
  kafka-data:

